# render.yaml - Render deployment configuration for Volley Stats app

services:
  # Backend API Service (Flask)
  - type: web
    name: volley-stats-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./application/server/Dockerfile
    dockerContext: ./application/server    
    envVars:
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://volley-stats.onrender.com
      - key: HUGGINGFACE_TOKEN
        sync: false
    healthCheckPath: /api/health
    autoDeploy: false

  # Frontend Static Site (React)
  - type: web
    name: volley-stats-ui
    runtime: static
    region: oregon
    plan: free
    rootDir: application/client
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://volley-stats-api.onrender.com
      - key: NODE_ENV
        value: production

# Database (if needed in future)
# databases:
#   - name: volley-stats-db
#     region: oregon
#     plan: free
#     databaseName: volley_stats
#     user: volley_admin

# Redis cache (if needed for session management)
# - type: redis
#   name: volley-stats-cache
#   region: oregon
#   plan: free
#   maxmemoryPolicy: allkeys-lru
#   ipAllowList: []