version: '3.8'

services:
  api:
    build: .
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - RENDER=true
      - FLASK_ENV=production
      - CORS_ORIGINS=http://localhost:5173
      - PYTHONUNBUFFERED=1
      # Add your HuggingFace token if needed
      # - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
